// Code generated by protoc-gen-go. DO NOT EDIT.
// source: net/protobuf/transmitter.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The client driver
type ClientDriver struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ProtocolVersion      int32    `protobuf:"varint,2,opt,name=protocolVersion" json:"protocolVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientDriver) Reset()         { *m = ClientDriver{} }
func (m *ClientDriver) String() string { return proto.CompactTextString(m) }
func (*ClientDriver) ProtoMessage()    {}
func (*ClientDriver) Descriptor() ([]byte, []int) {
	return fileDescriptor_transmitter_015262a61404b946, []int{0}
}
func (m *ClientDriver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientDriver.Unmarshal(m, b)
}
func (m *ClientDriver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientDriver.Marshal(b, m, deterministic)
}
func (dst *ClientDriver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientDriver.Merge(dst, src)
}
func (m *ClientDriver) XXX_Size() int {
	return xxx_messageInfo_ClientDriver.Size(m)
}
func (m *ClientDriver) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientDriver.DiscardUnknown(m)
}

var xxx_messageInfo_ClientDriver proto.InternalMessageInfo

func (m *ClientDriver) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClientDriver) GetProtocolVersion() int32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

// Server settings and informations
type ServerInformations struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ProtocolVersion      int32    `protobuf:"varint,3,opt,name=protocolVersion" json:"protocolVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInformations) Reset()         { *m = ServerInformations{} }
func (m *ServerInformations) String() string { return proto.CompactTextString(m) }
func (*ServerInformations) ProtoMessage()    {}
func (*ServerInformations) Descriptor() ([]byte, []int) {
	return fileDescriptor_transmitter_015262a61404b946, []int{1}
}
func (m *ServerInformations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInformations.Unmarshal(m, b)
}
func (m *ServerInformations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInformations.Marshal(b, m, deterministic)
}
func (dst *ServerInformations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInformations.Merge(dst, src)
}
func (m *ServerInformations) XXX_Size() int {
	return xxx_messageInfo_ServerInformations.Size(m)
}
func (m *ServerInformations) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInformations.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInformations proto.InternalMessageInfo

func (m *ServerInformations) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerInformations) GetProtocolVersion() int32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

// The server give to the client all the informations about him on the server
type HandshakeRequest struct {
	Uid                  string              `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	ServerInformations   *ServerInformations `protobuf:"bytes,2,opt,name=serverInformations" json:"serverInformations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HandshakeRequest) Reset()         { *m = HandshakeRequest{} }
func (m *HandshakeRequest) String() string { return proto.CompactTextString(m) }
func (*HandshakeRequest) ProtoMessage()    {}
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transmitter_015262a61404b946, []int{2}
}
func (m *HandshakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeRequest.Unmarshal(m, b)
}
func (m *HandshakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeRequest.Marshal(b, m, deterministic)
}
func (dst *HandshakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeRequest.Merge(dst, src)
}
func (m *HandshakeRequest) XXX_Size() int {
	return xxx_messageInfo_HandshakeRequest.Size(m)
}
func (m *HandshakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeRequest proto.InternalMessageInfo

func (m *HandshakeRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *HandshakeRequest) GetServerInformations() *ServerInformations {
	if m != nil {
		return m.ServerInformations
	}
	return nil
}

// The client respond with the informations about him, like the driver he use
type HandshakeResponse struct {
	ClientDriver         *ClientDriver `protobuf:"bytes,1,opt,name=clientDriver" json:"clientDriver,omitempty"`
	Token                string        `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HandshakeResponse) Reset()         { *m = HandshakeResponse{} }
func (m *HandshakeResponse) String() string { return proto.CompactTextString(m) }
func (*HandshakeResponse) ProtoMessage()    {}
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transmitter_015262a61404b946, []int{3}
}
func (m *HandshakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeResponse.Unmarshal(m, b)
}
func (m *HandshakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeResponse.Marshal(b, m, deterministic)
}
func (dst *HandshakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeResponse.Merge(dst, src)
}
func (m *HandshakeResponse) XXX_Size() int {
	return xxx_messageInfo_HandshakeResponse.Size(m)
}
func (m *HandshakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeResponse proto.InternalMessageInfo

func (m *HandshakeResponse) GetClientDriver() *ClientDriver {
	if m != nil {
		return m.ClientDriver
	}
	return nil
}

func (m *HandshakeResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type PeerItem struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerItem) Reset()         { *m = PeerItem{} }
func (m *PeerItem) String() string { return proto.CompactTextString(m) }
func (*PeerItem) ProtoMessage()    {}
func (*PeerItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_transmitter_015262a61404b946, []int{4}
}
func (m *PeerItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerItem.Unmarshal(m, b)
}
func (m *PeerItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerItem.Marshal(b, m, deterministic)
}
func (dst *PeerItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerItem.Merge(dst, src)
}
func (m *PeerItem) XXX_Size() int {
	return xxx_messageInfo_PeerItem.Size(m)
}
func (m *PeerItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerItem.DiscardUnknown(m)
}

var xxx_messageInfo_PeerItem proto.InternalMessageInfo

func (m *PeerItem) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type SubscribeToChannelRequest struct {
	Channel              string            `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Password             string            `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	RoutingKeys          []string          `protobuf:"bytes,3,rep,name=routingKeys" json:"routingKeys,omitempty"`
	Opts                 map[string]string `protobuf:"bytes,4,rep,name=opts" json:"opts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SubscribeToChannelRequest) Reset()         { *m = SubscribeToChannelRequest{} }
func (m *SubscribeToChannelRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeToChannelRequest) ProtoMessage()    {}
func (*SubscribeToChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transmitter_015262a61404b946, []int{5}
}
func (m *SubscribeToChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeToChannelRequest.Unmarshal(m, b)
}
func (m *SubscribeToChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeToChannelRequest.Marshal(b, m, deterministic)
}
func (dst *SubscribeToChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeToChannelRequest.Merge(dst, src)
}
func (m *SubscribeToChannelRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeToChannelRequest.Size(m)
}
func (m *SubscribeToChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeToChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeToChannelRequest proto.InternalMessageInfo

func (m *SubscribeToChannelRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *SubscribeToChannelRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SubscribeToChannelRequest) GetRoutingKeys() []string {
	if m != nil {
		return m.RoutingKeys
	}
	return nil
}

func (m *SubscribeToChannelRequest) GetOpts() map[string]string {
	if m != nil {
		return m.Opts
	}
	return nil
}

type SubscribeToChannelResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeToChannelResponse) Reset()         { *m = SubscribeToChannelResponse{} }
func (m *SubscribeToChannelResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeToChannelResponse) ProtoMessage()    {}
func (*SubscribeToChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transmitter_015262a61404b946, []int{6}
}
func (m *SubscribeToChannelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeToChannelResponse.Unmarshal(m, b)
}
func (m *SubscribeToChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeToChannelResponse.Marshal(b, m, deterministic)
}
func (dst *SubscribeToChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeToChannelResponse.Merge(dst, src)
}
func (m *SubscribeToChannelResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeToChannelResponse.Size(m)
}
func (m *SubscribeToChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeToChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeToChannelResponse proto.InternalMessageInfo

func (m *SubscribeToChannelResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *SubscribeToChannelResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type CustomDataEvent struct {
	EventName            string   `protobuf:"bytes,1,opt,name=eventName" json:"eventName,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomDataEvent) Reset()         { *m = CustomDataEvent{} }
func (m *CustomDataEvent) String() string { return proto.CompactTextString(m) }
func (*CustomDataEvent) ProtoMessage()    {}
func (*CustomDataEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_transmitter_015262a61404b946, []int{7}
}
func (m *CustomDataEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomDataEvent.Unmarshal(m, b)
}
func (m *CustomDataEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomDataEvent.Marshal(b, m, deterministic)
}
func (dst *CustomDataEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomDataEvent.Merge(dst, src)
}
func (m *CustomDataEvent) XXX_Size() int {
	return xxx_messageInfo_CustomDataEvent.Size(m)
}
func (m *CustomDataEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomDataEvent.DiscardUnknown(m)
}

var xxx_messageInfo_CustomDataEvent proto.InternalMessageInfo

func (m *CustomDataEvent) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *CustomDataEvent) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type NewPeer struct {
	Peer                 *PeerItem `protobuf:"bytes,1,opt,name=peer" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NewPeer) Reset()         { *m = NewPeer{} }
func (m *NewPeer) String() string { return proto.CompactTextString(m) }
func (*NewPeer) ProtoMessage()    {}
func (*NewPeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_transmitter_015262a61404b946, []int{8}
}
func (m *NewPeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewPeer.Unmarshal(m, b)
}
func (m *NewPeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewPeer.Marshal(b, m, deterministic)
}
func (dst *NewPeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewPeer.Merge(dst, src)
}
func (m *NewPeer) XXX_Size() int {
	return xxx_messageInfo_NewPeer.Size(m)
}
func (m *NewPeer) XXX_DiscardUnknown() {
	xxx_messageInfo_NewPeer.DiscardUnknown(m)
}

var xxx_messageInfo_NewPeer proto.InternalMessageInfo

func (m *NewPeer) GetPeer() *PeerItem {
	if m != nil {
		return m.Peer
	}
	return nil
}

type RemovePeer struct {
	Peer                 *PeerItem `protobuf:"bytes,2,opt,name=peer" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RemovePeer) Reset()         { *m = RemovePeer{} }
func (m *RemovePeer) String() string { return proto.CompactTextString(m) }
func (*RemovePeer) ProtoMessage()    {}
func (*RemovePeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_transmitter_015262a61404b946, []int{9}
}
func (m *RemovePeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePeer.Unmarshal(m, b)
}
func (m *RemovePeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePeer.Marshal(b, m, deterministic)
}
func (dst *RemovePeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePeer.Merge(dst, src)
}
func (m *RemovePeer) XXX_Size() int {
	return xxx_messageInfo_RemovePeer.Size(m)
}
func (m *RemovePeer) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePeer.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePeer proto.InternalMessageInfo

func (m *RemovePeer) GetPeer() *PeerItem {
	if m != nil {
		return m.Peer
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientDriver)(nil), "transmitter.ClientDriver")
	proto.RegisterType((*ServerInformations)(nil), "transmitter.ServerInformations")
	proto.RegisterType((*HandshakeRequest)(nil), "transmitter.HandshakeRequest")
	proto.RegisterType((*HandshakeResponse)(nil), "transmitter.HandshakeResponse")
	proto.RegisterType((*PeerItem)(nil), "transmitter.PeerItem")
	proto.RegisterType((*SubscribeToChannelRequest)(nil), "transmitter.SubscribeToChannelRequest")
	proto.RegisterMapType((map[string]string)(nil), "transmitter.SubscribeToChannelRequest.OptsEntry")
	proto.RegisterType((*SubscribeToChannelResponse)(nil), "transmitter.SubscribeToChannelResponse")
	proto.RegisterType((*CustomDataEvent)(nil), "transmitter.CustomDataEvent")
	proto.RegisterType((*NewPeer)(nil), "transmitter.NewPeer")
	proto.RegisterType((*RemovePeer)(nil), "transmitter.RemovePeer")
}

func init() {
	proto.RegisterFile("net/protobuf/transmitter.proto", fileDescriptor_transmitter_015262a61404b946)
}

var fileDescriptor_transmitter_015262a61404b946 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x55, 0xbe, 0xda, 0x78, 0x1c, 0xa9, 0x65, 0x05, 0xc8, 0x8d, 0x2a, 0xb0, 0x7c, 0x32, 0x97,
	0x14, 0x05, 0xa4, 0x22, 0x24, 0x2e, 0x24, 0x95, 0xa8, 0x40, 0x29, 0xda, 0x22, 0x0e, 0xdc, 0x36,
	0xc9, 0x94, 0x58, 0xb1, 0x77, 0xcd, 0xee, 0xd8, 0x55, 0xfe, 0x36, 0xbf, 0x00, 0x79, 0x63, 0xa7,
	0x36, 0x09, 0xa2, 0xb7, 0x79, 0x4f, 0x7e, 0x6f, 0x66, 0xde, 0xac, 0xe1, 0x85, 0x44, 0xba, 0x48,
	0xb5, 0x22, 0x35, 0xcf, 0xee, 0x2e, 0x48, 0x0b, 0x69, 0x92, 0x88, 0x08, 0xf5, 0xc8, 0x92, 0xcc,
	0xad, 0x51, 0xc1, 0x17, 0x18, 0x4c, 0xe2, 0x08, 0x25, 0x4d, 0x75, 0x94, 0xa3, 0x66, 0x0c, 0xba,
	0x52, 0x24, 0xe8, 0xb5, 0xfc, 0x56, 0xe8, 0x70, 0x5b, 0xb3, 0x10, 0x4e, 0xac, 0x72, 0xa1, 0xe2,
	0xef, 0xa8, 0x4d, 0xa4, 0xa4, 0xd7, 0xf6, 0x5b, 0x61, 0x8f, 0xff, 0x4d, 0x07, 0x1c, 0xd8, 0x2d,
	0xea, 0x1c, 0xf5, 0xb5, 0xbc, 0x53, 0x3a, 0x11, 0x14, 0x29, 0x69, 0x1e, 0xeb, 0xd9, 0x39, 0xec,
	0x99, 0xc1, 0xe9, 0x27, 0x21, 0x97, 0x66, 0x25, 0xd6, 0xc8, 0xf1, 0x57, 0x86, 0x86, 0xd8, 0x29,
	0x74, 0xb2, 0x68, 0x59, 0x1a, 0x16, 0x25, 0xbb, 0x01, 0x66, 0xf6, 0x3a, 0xdb, 0x31, 0xdd, 0xf1,
	0xcb, 0x51, 0x3d, 0x84, 0xfd, 0x01, 0xf9, 0x01, 0x69, 0xb0, 0x82, 0x27, 0xb5, 0xb6, 0x26, 0x55,
	0xd2, 0x20, 0xfb, 0x00, 0x83, 0x45, 0x2d, 0x2d, 0x3b, 0x80, 0x3b, 0x3e, 0x6b, 0xf8, 0xd7, 0xe3,
	0xe4, 0x8d, 0xcf, 0xd9, 0x53, 0xe8, 0x91, 0x5a, 0xe3, 0x36, 0x3e, 0x87, 0x6f, 0x41, 0x70, 0x0e,
	0xfd, 0xaf, 0x88, 0xfa, 0x9a, 0x30, 0xd9, 0x5f, 0x2c, 0xf8, 0xdd, 0x82, 0xb3, 0xdb, 0x6c, 0x6e,
	0x16, 0x3a, 0x9a, 0xe3, 0x37, 0x35, 0x59, 0x09, 0x29, 0x31, 0xae, 0x82, 0xf0, 0xe0, 0x78, 0xb1,
	0x65, 0x4a, 0x4d, 0x05, 0xd9, 0x10, 0xfa, 0xa9, 0x30, 0xe6, 0x5e, 0xe9, 0x65, 0xd9, 0x6e, 0x87,
	0x99, 0x0f, 0xae, 0x56, 0x19, 0x45, 0xf2, 0xe7, 0x67, 0xdc, 0x18, 0xaf, 0xe3, 0x77, 0x42, 0x87,
	0xd7, 0x29, 0x36, 0x85, 0xae, 0x4a, 0xc9, 0x78, 0x5d, 0xbf, 0x13, 0xba, 0xe3, 0xd7, 0xcd, 0x00,
	0xff, 0x35, 0xcd, 0xe8, 0x26, 0x25, 0x73, 0x25, 0x49, 0x6f, 0xb8, 0x55, 0x0f, 0x2f, 0xc1, 0xd9,
	0x51, 0xc5, 0x6a, 0x6b, 0xdc, 0x54, 0xab, 0xad, 0x71, 0x53, 0xc4, 0x91, 0x8b, 0x38, 0xc3, 0x2a,
	0x0e, 0x0b, 0xde, 0xb7, 0xdf, 0xb5, 0x82, 0x19, 0x0c, 0x0f, 0x75, 0x29, 0xaf, 0xf0, 0x1c, 0x8e,
	0x34, 0x9a, 0x2c, 0x26, 0x6b, 0xd6, 0xe3, 0x25, 0xb2, 0x61, 0xa8, 0x24, 0x41, 0x49, 0xa5, 0x63,
	0x05, 0x83, 0x09, 0x9c, 0x4c, 0x32, 0x43, 0x2a, 0x99, 0x0a, 0x12, 0x57, 0x39, 0x4a, 0x62, 0xe7,
	0xe0, 0x60, 0x51, 0xcc, 0x1e, 0x5e, 0xe6, 0x03, 0x51, 0x3c, 0xd9, 0xa5, 0x20, 0x61, 0x7d, 0x06,
	0xdc, 0xd6, 0xc1, 0x5b, 0x38, 0x9e, 0xe1, 0x7d, 0x71, 0x2a, 0xf6, 0x0a, 0xba, 0x29, 0xee, 0xee,
	0xff, 0xac, 0x11, 0x4f, 0x75, 0x4b, 0x6e, 0x3f, 0x09, 0x2e, 0x01, 0x38, 0x26, 0x2a, 0xc7, 0x86,
	0xb0, 0xfd, 0x5f, 0xe1, 0x47, 0xf8, 0xd1, 0xaf, 0x7e, 0xe2, 0xf9, 0x91, 0xad, 0xde, 0xfc, 0x09,
	0x00, 0x00, 0xff, 0xff, 0xab, 0x36, 0xa1, 0xd4, 0xdb, 0x03, 0x00, 0x00,
}
