// Code generated by protoc-gen-go. DO NOT EDIT.
// source: net/protobuf/transmitter.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The client driver
type ClientDriver struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ProtocolVersion      int32    `protobuf:"varint,2,opt,name=protocolVersion" json:"protocolVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientDriver) Reset()         { *m = ClientDriver{} }
func (m *ClientDriver) String() string { return proto.CompactTextString(m) }
func (*ClientDriver) ProtoMessage()    {}
func (*ClientDriver) Descriptor() ([]byte, []int) {
	return fileDescriptor_transmitter_708cdcf03883de8f, []int{0}
}
func (m *ClientDriver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientDriver.Unmarshal(m, b)
}
func (m *ClientDriver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientDriver.Marshal(b, m, deterministic)
}
func (dst *ClientDriver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientDriver.Merge(dst, src)
}
func (m *ClientDriver) XXX_Size() int {
	return xxx_messageInfo_ClientDriver.Size(m)
}
func (m *ClientDriver) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientDriver.DiscardUnknown(m)
}

var xxx_messageInfo_ClientDriver proto.InternalMessageInfo

func (m *ClientDriver) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClientDriver) GetProtocolVersion() int32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

// Server settings and informations
type ServerInformations struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ProtocolVersion      int32    `protobuf:"varint,3,opt,name=protocolVersion" json:"protocolVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInformations) Reset()         { *m = ServerInformations{} }
func (m *ServerInformations) String() string { return proto.CompactTextString(m) }
func (*ServerInformations) ProtoMessage()    {}
func (*ServerInformations) Descriptor() ([]byte, []int) {
	return fileDescriptor_transmitter_708cdcf03883de8f, []int{1}
}
func (m *ServerInformations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInformations.Unmarshal(m, b)
}
func (m *ServerInformations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInformations.Marshal(b, m, deterministic)
}
func (dst *ServerInformations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInformations.Merge(dst, src)
}
func (m *ServerInformations) XXX_Size() int {
	return xxx_messageInfo_ServerInformations.Size(m)
}
func (m *ServerInformations) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInformations.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInformations proto.InternalMessageInfo

func (m *ServerInformations) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerInformations) GetProtocolVersion() int32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

// The server give to the client all the informations about him on the server
type HandshakeRequest struct {
	Uid                  string              `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	ServerInformations   *ServerInformations `protobuf:"bytes,2,opt,name=serverInformations" json:"serverInformations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HandshakeRequest) Reset()         { *m = HandshakeRequest{} }
func (m *HandshakeRequest) String() string { return proto.CompactTextString(m) }
func (*HandshakeRequest) ProtoMessage()    {}
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transmitter_708cdcf03883de8f, []int{2}
}
func (m *HandshakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeRequest.Unmarshal(m, b)
}
func (m *HandshakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeRequest.Marshal(b, m, deterministic)
}
func (dst *HandshakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeRequest.Merge(dst, src)
}
func (m *HandshakeRequest) XXX_Size() int {
	return xxx_messageInfo_HandshakeRequest.Size(m)
}
func (m *HandshakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeRequest proto.InternalMessageInfo

func (m *HandshakeRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *HandshakeRequest) GetServerInformations() *ServerInformations {
	if m != nil {
		return m.ServerInformations
	}
	return nil
}

// The client respond with the informations about him, like the driver he use
type HandshakeResponse struct {
	ClientDriver         *ClientDriver `protobuf:"bytes,1,opt,name=clientDriver" json:"clientDriver,omitempty"`
	Token                string        `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HandshakeResponse) Reset()         { *m = HandshakeResponse{} }
func (m *HandshakeResponse) String() string { return proto.CompactTextString(m) }
func (*HandshakeResponse) ProtoMessage()    {}
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transmitter_708cdcf03883de8f, []int{3}
}
func (m *HandshakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeResponse.Unmarshal(m, b)
}
func (m *HandshakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeResponse.Marshal(b, m, deterministic)
}
func (dst *HandshakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeResponse.Merge(dst, src)
}
func (m *HandshakeResponse) XXX_Size() int {
	return xxx_messageInfo_HandshakeResponse.Size(m)
}
func (m *HandshakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeResponse proto.InternalMessageInfo

func (m *HandshakeResponse) GetClientDriver() *ClientDriver {
	if m != nil {
		return m.ClientDriver
	}
	return nil
}

func (m *HandshakeResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SubscribeToChannelRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	RoutingKeys          []string `protobuf:"bytes,3,rep,name=routingKeys" json:"routingKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeToChannelRequest) Reset()         { *m = SubscribeToChannelRequest{} }
func (m *SubscribeToChannelRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeToChannelRequest) ProtoMessage()    {}
func (*SubscribeToChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transmitter_708cdcf03883de8f, []int{4}
}
func (m *SubscribeToChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeToChannelRequest.Unmarshal(m, b)
}
func (m *SubscribeToChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeToChannelRequest.Marshal(b, m, deterministic)
}
func (dst *SubscribeToChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeToChannelRequest.Merge(dst, src)
}
func (m *SubscribeToChannelRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeToChannelRequest.Size(m)
}
func (m *SubscribeToChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeToChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeToChannelRequest proto.InternalMessageInfo

func (m *SubscribeToChannelRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SubscribeToChannelRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SubscribeToChannelRequest) GetRoutingKeys() []string {
	if m != nil {
		return m.RoutingKeys
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientDriver)(nil), "transmitter.ClientDriver")
	proto.RegisterType((*ServerInformations)(nil), "transmitter.ServerInformations")
	proto.RegisterType((*HandshakeRequest)(nil), "transmitter.HandshakeRequest")
	proto.RegisterType((*HandshakeResponse)(nil), "transmitter.HandshakeResponse")
	proto.RegisterType((*SubscribeToChannelRequest)(nil), "transmitter.SubscribeToChannelRequest")
}

func init() {
	proto.RegisterFile("net/protobuf/transmitter.proto", fileDescriptor_transmitter_708cdcf03883de8f)
}

var fileDescriptor_transmitter_708cdcf03883de8f = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x31, 0x4f, 0x02, 0x41,
	0x10, 0x85, 0x83, 0x27, 0x06, 0xe6, 0x48, 0xc4, 0x8d, 0x05, 0x58, 0xe8, 0xe5, 0xaa, 0xab, 0x20,
	0xc1, 0xda, 0x46, 0x2c, 0x34, 0x9a, 0x98, 0x2c, 0xc6, 0xc2, 0x6e, 0x0f, 0x06, 0xd9, 0xc0, 0xcd,
	0xe2, 0xcc, 0x1e, 0xc6, 0x7f, 0x6f, 0x3c, 0xc0, 0x2c, 0x42, 0x61, 0xf7, 0xe6, 0xe5, 0xe6, 0xcd,
	0xbb, 0x2f, 0x0b, 0x97, 0x84, 0xbe, 0xbf, 0x64, 0xe7, 0x5d, 0x5e, 0x4e, 0xfb, 0x9e, 0x0d, 0x49,
	0x61, 0xbd, 0x47, 0xee, 0x55, 0xa6, 0x8a, 0x03, 0x2b, 0x7d, 0x82, 0xd6, 0x70, 0x61, 0x91, 0xfc,
	0x1d, 0xdb, 0x15, 0xb2, 0x52, 0x70, 0x4c, 0xa6, 0xc0, 0x4e, 0x2d, 0xa9, 0x65, 0x4d, 0x5d, 0x69,
	0x95, 0xc1, 0x69, 0xb5, 0x39, 0x76, 0x8b, 0x57, 0x64, 0xb1, 0x8e, 0x3a, 0x47, 0x49, 0x2d, 0xab,
	0xeb, 0xbf, 0x76, 0xaa, 0x41, 0x8d, 0x90, 0x57, 0xc8, 0x0f, 0x34, 0x75, 0x5c, 0x18, 0x6f, 0x1d,
	0xc9, 0x7f, 0x33, 0xa3, 0xc3, 0x99, 0x25, 0xb4, 0xef, 0x0d, 0x4d, 0x64, 0x66, 0xe6, 0xa8, 0xf1,
	0xa3, 0x44, 0xf1, 0xaa, 0x0d, 0x51, 0x69, 0x27, 0x9b, 0xc0, 0x1f, 0xa9, 0x9e, 0x41, 0xc9, 0xde,
	0xe5, 0xaa, 0x66, 0x3c, 0xb8, 0xea, 0x85, 0x10, 0xf6, 0x0b, 0xea, 0x03, 0xab, 0xe9, 0x0c, 0xce,
	0x82, 0xb3, 0xb2, 0x74, 0x24, 0xa8, 0x6e, 0xa0, 0x35, 0x0e, 0x68, 0x55, 0x05, 0xe2, 0x41, 0x77,
	0x27, 0x3f, 0xc4, 0xa9, 0x77, 0x3e, 0x57, 0xe7, 0x50, 0xf7, 0x6e, 0x8e, 0x6b, 0x7c, 0x4d, 0xbd,
	0x1e, 0xd2, 0x02, 0xba, 0xa3, 0x32, 0x97, 0x31, 0xdb, 0x1c, 0x5f, 0xdc, 0x70, 0x66, 0x88, 0x70,
	0xb1, 0xfd, 0xd3, 0x43, 0xec, 0x2e, 0xa0, 0xb1, 0x34, 0x22, 0x9f, 0x8e, 0x27, 0x9b, 0xa4, 0xdf,
	0x59, 0x25, 0x10, 0xb3, 0x2b, 0xbd, 0xa5, 0xf7, 0x47, 0xfc, 0x92, 0x4e, 0x94, 0x44, 0x59, 0x53,
	0x87, 0xd6, 0x2d, 0xbc, 0x35, 0xb6, 0x8f, 0x23, 0x3f, 0xa9, 0xd4, 0xf5, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf4, 0xdf, 0x3b, 0x5b, 0x33, 0x02, 0x00, 0x00,
}
